import {
  MessageCircle,
  Heart,
  Repeat2,
  MoreHorizontal,
  ArrowLeft,
  CalendarDays,
  Home,
  Bell,
  BellDot,
  Search,
  Mail,
  User2,
  FileImage,
  X,
  Lock,
  ImagePlus,
  LogOut,
  UserCheck
} from 'lucide-react'

export const Icons = {
  MessageCircle: MessageCircle,
  Heart: Heart,
  Repeat2: Repeat2,
  Home: Home,
  Bell: Bell,
  BellDot: BellDot,
  Messages: Mail,
  Profile: User2,
  MoreHorizontal: MoreHorizontal,
  ArrowLeft: ArrowLeft,
  CalendarDays: CalendarDays,
  FileImage: FileImage,
  Close: X,
  Lock: Lock,
  Search: Search,
  FileImage: FileImage,
  ImagePlus: ImagePlus,
  LogOut: LogOut,
  UserCheck: UserCheck
}
